### ISSUE TITLE
romeo dcm packages release

### ISSUE THREAD

**Issue by keulYSMB** [ros-aldebaran/romeo_robot#6]
Anybody actually tested the released packages for dcm ? 
Given that the sdk is not provided, the nodes are not compiled so you cannot run any dcm node out of the box. Does it make sense to keep releasing them ? cf. discussion on this thread https://github.com/ros-aldebaran/nao_dcm_robot/issues/9

**Comment by nlyubova** [comment]
Never tested released but the source works well!

I can test the released one on Monday (since I need a real robot, right?)?

**Comment by keulYSMB** [comment]
You don't necessarly need a robot, I just installed the package and ran:
roslaunch romeo_dcm_bringup romeo_dcm_bringup_remote.launch
and I have the error popping up directly ERROR: cannot launch node of type
[romeo_dcm_driver/romeo_dcm_driver]: can't locate node [romeo_dcm_driver]
in package [romeo_dcm_driver]

But yes I'm sure the sources works well, it's just that the ros buildfarms
don't have the naoqi sdk installed so they basically install just the
launchfiles and the configuration files but not the nodes.

**Comment by vrabaud** [comment]
That was a mistake. I am removing those packages from release.
BTW, the dcm_msgs package should be removed en use the standard: http://docs.ros.org/api/std_srvs/html/srv/SetBool.html (to simplify maintenance).

**Comment by vrabaud** [comment]
Fixed in https://github.com/ros-aldebaran/romeo_robot-release/commit/f0b54eef0bdaa4f853bf352de46a70acb63ad6d3 and released in https://github.com/ros/rosdistro/pull/10493 and https://github.com/ros/rosdistro/pull/10494

**Comment by vrabaud** [comment]
@hris2003 , guys, be ready to receive a bunch of failure emails. The buildfarm does not handle the deletion of packages properly (I told the buildfarm guys).
