### ISSUE TITLE
Build romeo_dcm_driver with naoqi-sdk-2.3.0.14-linux64

### ISSUE THREAD

**Issue by jokla** [ros-aldebaran/romeo_robot#9]
Hi!

I am trying to build the package romeo_robot  using the `naoqi-sdk-2.3.0.14-linux64` but I have a problem with `romeo_dcm_driver`.

First error:

-- Could not find NAOqi's qitype
-- Boost version: 1.54.0
-- Cannot find NAOqi C++ sdk; C++ nodes will NOT be built

In fact in the FindNAOqi.cmake we are looking for the library **qitype** that doesn't exist anymore in naoqi-sdk-2.3.0.14. Was it merged with the lib qi? (I can find it in the folder /naoqi-sdk-2.3.0.14-linux64/include/qi/type).

If I uncomment qitype from the set(NAOqi_COMPONENTS) and in the CMakeLists.txt I get this errors:

```
CMakeFiles/romeo_dcm_driver.dir/src/romeo_driver.cpp.o:(.rodata._ZTIN2qi14TypeOfTemplateINS_10FutureSyncEEE[_ZTIN2qi14TypeOfTemplateINS_10FutureSyncEEE]+0x10): undefined reference to `typeinfo for qi::detail::StaticObjectTypeBase'
CMakeFiles/romeo_dcm_driver.dir/src/romeo_driver.cpp.o:(.rodata._ZTIN2qi14TypeOfTemplateINS_6FutureEEE[_ZTIN2qi14TypeOfTemplateINS_6FutureEEE]+0x10): undefined reference to `typeinfo for qi::detail::StaticObjectTypeBase'
CMakeFiles/romeo_dcm_driver.dir/src/romeo.cpp.o:(.rodata._ZTV5Romeo[_ZTV5Romeo]+0x48): undefined reference to `qi::DynamicObject::metaProperty(qi::Object<qi::Empty>, unsigned int)'
CMakeFiles/romeo_dcm_driver.dir/src/romeo.cpp.o:(.rodata._ZTV5Romeo[_ZTV5Romeo]+0x50): undefined reference to `qi::DynamicObject::metaSetProperty(qi::Object<qi::Empty>, unsigned int, qi::AnyValue)'
```

Any idea?

Thanks in advance!

**Comment by nlyubova** [comment]
try with naoqi 2.1, it works

**Comment by jokla** [comment]
Thanks, I am using naoqi 2.1 and it is working.
I use the version 2.3 without ROS, so I was wondering how to solve this problem, but It is not blocking for me.

**Comment by mikaelarguedas** [comment]
@suryaambrose Any idea about what happened to qitype between naoqi2.1 and naoqi2.3 ? Any lead to solve the problem for future versions ?
Thanks!

**Comment by nlyubova** [comment]
@suryaambrose it disappeared :)

**Comment by suryaambrose** [comment]
Yeah they removed it. 
We probably need to do something in the FindNAOqi.cmake. I did fix something like that, but I can't remember in which project and as this file is duplicated among all naoqi projects, it is sometimes hard to keep a clear track :(. 

I'll look for it and come back to you

**Comment by nlyubova** [comment]
That would be nice to fix it since it is in many packages . Was in in naoqi_driver ?

**Comment by jokla** [comment]
Hi! 

Any news about the fix?

Thanks!

**Comment by nlyubova** [comment]
Try to remove qytype in CMakeLists.txt and in cmake/FindNAOqi.cmake. It worked for me, let me test it again and do a fix

**Comment by nlyubova** [comment]
Now this package is replaced by naoqi_dcm_driver that is much easy to compile. Should we close this issue?

**Comment by jokla** [comment]
@nlyubova yes! Thanks
